package se.yrgo.dataaccess;

import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.core.RowMapper;
import se.yrgo.domain.Call;
import se.yrgo.domain.Customer;

import java.sql.Date;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;

public class CustomerDaoJdbcTemplateImpl implements CustomerDao {
    private static final String DELETE_SQL = "DELETE FROM CUSTOMERS WHERE CUSTOMER_ID=?";
    private static final String UPDATE_SQL = "UPDATE CUSTOMERS SET COMPANY_NAME=?, EMAIL=?, TELEPHONE=?, NOTES=? WHERE CUSTOMER_ID=?";
    private static final String INSERT_SQL = "INSERT INTO CUSTOMERS (CUSTOMER_ID, COMPANY_NAME, EMAIL, TELEPHONE, NOTES) VALUES (?,?,?,?,?)";
    private static final String GET_CUSTOMERS_SQL = "SELECT CUSTOMER_ID, COMPANY_NAME, EMAIL, TELEPHONE, NOTES FROM CUSTOMERS";
    private final JdbcTemplate template;
    public CustomerDaoJdbcTemplateImpl(JdbcTemplate template) {
        this.template = template;
        try{
            template.update("DROP TABLE IF EXISTS CALLRECORDS");
            template.update("DROP TABLE IF EXISTS CUSTOMERS");
            template.update("CREATE TABLE CUSTOMERS (CUSTOMER_ID VARCHAR(10) PRIMARY KEY, COMPANY_NAME VARCHAR(25), EMAIL VARCHAR(50), TELEPHONE VARCHAR(15), NOTES VARCHAR(100))");
            template.update("CREATE TABLE CALLRECORDS (CALLRECORD_ID INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1), CUSTOMER_ID VARCHAR(10), TIME_AND_DATE DATE, NOTES VARCHAR(100), FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID))");
        }catch (org.springframework.jdbc.BadSqlGrammarException e){
            System.err.println(e.getSQLException().getMessage() + "\nPlease try again.");
        }
    }

    public void create(Customer customer){
        this.template.update(INSERT_SQL, customer.getCustomerId(), customer.getCompanyName(), customer.getEmail(), customer.getTelephone(), customer.getNotes());
    }

    public Customer getById(String customerId) throws RecordNotFoundException{
            return this.template.queryForObject(GET_CUSTOMERS_SQL + " WHERE CUSTOMER_ID=?", new CustomerRowMapper(), customerId);
    }

    public List<Customer> getByName(String name){
        return this.template.query(GET_CUSTOMERS_SQL + " WHERE COMPANY_NAME=?", new CustomerRowMapper(), name);
    }

    public void update(Customer customerToUpdate) throws RecordNotFoundException{
        this.template.update(UPDATE_SQL, customerToUpdate.getCompanyName(),
                customerToUpdate.getEmail(), customerToUpdate.getTelephone(),
                customerToUpdate.getNotes(), customerToUpdate.getCustomerId());
    }

    public void delete(Customer oldCustomer) throws RecordNotFoundException{
        this.template.update(DELETE_SQL, oldCustomer);
    }

    public List<Customer> getAllCustomers(){
        return this.template.query(GET_CUSTOMERS_SQL, new CustomerRowMapper());
    }

    public Customer getFullCustomerDetail(String customerId) throws RecordNotFoundException{
        Customer c = getById(customerId);
        List<Call> calls = this.template.query("SELECT * FROM CALLRECORDS CR INNER JOIN CUSTOMERS C ON C.CUSTOMER_ID = CR.CUSTOMER_ID WHERE CR.CUSTOMER_ID=?", new CallRowMapper(), c.getCustomerId());
        c.setCalls(calls);
        return c;
    }

    public void addCall (Call newCall, String customerId) throws RecordNotFoundException{
        Customer c = getFullCustomerDetail(customerId);
        c.addCall(newCall);
    }
}
class CustomerRowMapper implements RowMapper<Customer> {
    public Customer mapRow(ResultSet rs, int arg1) throws SQLException {
        String customerId = rs.getString(1);
        String companyName = rs.getString(2);
        String email = rs.getString(3);
        String telephone = rs.getString(4);
        String notes = rs.getString(5);

        return new Customer("" + customerId, companyName, email, telephone, notes);
    }
}
class   CallRowMapper implements RowMapper<Call> {
    public Call mapRow(ResultSet rs, int arg1) throws SQLException {
        Date date = rs.getDate(3);
        String notes = rs.getString(4);

        return new Call(notes, date);
    }
}